apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: app-efs-sc
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume-group: staging-monitor