apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
        - name: redis-server
          image: redis:latest
          ports:
            - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-server
  namespace: dev
  labels:
    app: redis-server
spec:
  type: ClusterIP
  selector:
    app: redis-server
  ports:
    - port: 6379
      name: redis-server
      targetPort: 6379
      protocol: TCP