apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: status-page-pvc-dev
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: app-efs-sc
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume-group: staging-app-dev