apiVersion: v1
kind: PersistentVolume
metadata:
  name: status-page-pv-dev
  namespace: dev
  labels:
    volume-group: staging-app-dev
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: app-efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-09de73123159e568b
