apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-dolana-proj
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AnnaGreenboym/dolana-statuspage.git
    targetRevision: main
    path: k8s_resources
    plugin:
      name: kustomize-envsubst
  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
